### ISSUE TITLE
Use "Oracles" instead of "External Non-authoritative, Non-deterministic Data"

### ISSUE THREAD

**Issue by chaals** [eea-oasis/baseline-standard#125]
Simpler phrase, very widely understood in the blockchain world, and doesn't really have an ambiguity in general understanding (because it's otherwise not meaningful).

This would simplify reading, and for people used to the term it would be instantly clear what it's about.

**Comment by Therecanbeonlyone1969** [comment]
@chaals ... the world `Oracle` is not precise enough to be used in the context of this standard because it can be authoritative and deterministic (atomic clock, block hash etc.) as well as non-authoritative and non-deterministic (weather.com, odds of Tom Brady winning another Super Bowl from ONE bookie etc.) or any combination. Also, it is wildly misused and abused in the blockchain ecosystem such as the word wallet. This also needs to be understandable by non-blockchain IT professionals who are the primary audience of this standard.

**Comment by Therecanbeonlyone1969** [comment]
@chaals ... per decision in the WG meeting, please, respond to the above response. Otherwise, the issue will be closed at the next WG meeting.

**Comment by chaals** [comment]
I disagree that the complex phrase used helps anyone to understand, and I disagree that it is less confusing than the term "oracle" (which we can define, to help reduce confusion among the people who read the glossary).

But this is an editorial decision, so with my disagreement noted I won't continue the discussion.
