### ISSUE TITLE
Reconcile / merge R247, R258, R262?

### ISSUE THREAD

**Issue by chaals** [eea-oasis/baseline-standard#97]
[R247] says an account must have a deterministic nonce. That seems underspecified - it must use a (linearly?) increasing sequence as nonces, no?

At which point, R258 seems odd, unless it means that a transaction should be rejected if it doesn't have "the right" nonce (according to some test)

Maybe it's a separate issue, but under R262 a transaction has to be processed before another can be accepted - an account that attempts to send out more than one at a time will mess up its nonces and be broken...

**Comment by Therecanbeonlyone1969** [comment]
> [R247] says an account must have a deterministic nonce. That seems underspecified - it must use a (linearly?) increasing sequence as nonces, no?

No. Linearly increasing is one form of a deterministic nonce but not the only one. A nested hash is also strictly deterministic.

> At which point, R258 seems odd, unless it means that a transaction should be rejected if it doesn't have "the right" nonce (according to some test)

That is correct, the wording "based on the account of the sender" is important. This implies a reference to a previous nonce state because each account must have a deterministic nonce and you cannot reuse a nonce, because then it would not be deterministic anymore.

> Maybe it's a separate issue, but under R262 a transaction has to be processed before another can be accepted - an account that attempts to send out more than one at a time will mess up its nonces and be broken...

No, not necessarily. In Ethereum, an account can send out more than 1 transaction at a time as long as the nonce increases linearly and, the transactions are processed in the correct order. If 2 of three fail because n+2 is processed before n+1 just means that the n+2 transaction must be submitted again.

There is, however, a small issue with [262].

> The transaction nonce is not equal to the account nonce plus 1.

-> The transaction nonce is not equal to the account nonce plus the next deterministic nonce-step.

the "plus 1" is a specific deterministic algorithm. It must have been late when I wrote that.

cc @chaals
